---
title: "Guidance on Phases"
format: html
editor: 
  markdown: 
    wrap: 72
---

## Phases Basics

-   Phases are a way of switching on the estimation of parameters in a
    specified order. A negative phase means that you are fixing a
    parameter and it is not estimated, a positive phase means that you
    want the model to estimate the parameter. Most models use 3 to 5
    phases. Parameters that enter in an early stage remain active as
    other parameters become active.

-   You can spread out when you estimate parameters using phases. **In some cases, 
    can speed up your model or help with convergence.**

-   How you spread it out is up to you. Below is some general guidance
    on assigning phases.

## A Note about Phases

There is really no ***one*** way or even ***best*** general way of
assigning phases.

This general guidance may not accommodate every model or
necessarily give you the best model fit. However, it may provide a
starting point when initially trying to assign phases to parameters.

If you are an experienced SS3 user with additional suggestions for
phasing, please let us know by submitting an issue in this repository.
We will gladly review and incorporate those into this guidance.

## A Guide to Parameter Phasing in Stock Synthesis

*This guide is largely taken from the [Stock Assessment Continuum
Tool](https://github.com/shcaba/SS-DL-tool) as provided by André Punt*

#### General

-   Get the scale of the population right first. First estimate the
    parameter that determines scale in an SS3 model ($R_{0}$ - expected
    recruitment in an unfished state) then refine the model fit by
    adding parameters.
-   The parameters are added at each phase so, for example, the
    parameters that are estimated in phase 3 are those estimated in
    phase 2 ***plus*** those designated as to be estimated in phase 3.
-   The phasing sequence should not matter but (a) good phasing can
    speed things up, (b) bad phasing can lead to the estimation being
    trapped in a local minimum, and (c) jittering™ can help to assess
    how reliable the final estimates are.
-   The schema below is based on eight phases but, sometimes I will
    "skip a phase", e.g. place the other "annual deviations" in phase 9
    rather than phase 8 (And estimate no "new" parameters in phase 8) to
    allow the estimation method to better characterize the parameters
    estimated in phases 1-7.

**André's preferred order:**

1.  Start with an "Age-structured Production Model", estimating $R_{0}$ and
    catchability, Q.

2.  Add recruitment deviations (as these can pick up signals from the
    age and length data on cohort size) (at this point your model is
    analogous to JABBA)

3.  Now estimate the base selectivity \[and retention\] parameters
    (enabling this to be refined)

4.  Now estimate growth

5.  Now estimate natural mortality, $M$ (if feeling brave!)

6.  Now estimate steepness, h (h may hit an unrealistic bound, i.e., 0.2
    or 1 - if the data are in conflict so be wary)

7.  Now estimate the other annual deviations (e.g., annual deviations on
    kappa or age-year deviations on selectivity).

8.  Finally environmental linkages, e.g., between recruitment and an
    environmental variable such as temperature.

#### Other ways of tackling phases (per Jason Cope)

-   Start life history parameters (growth and sometimes mortality) 
    estimation in phase 3 or even phase 2.
-   Leave selectivity until phases 3 or 4 (after life history) IF you
    have decent starting values for selectivity already.

#### Some additional notes (per Rick Methot)

-   Be careful with many phases unless you have good initial values for
    the un-estimated parameters.

-   Parameters with high correlation usually should be estimated in the
    same phase, so ADMB can change them in sync.

-   Examine your composition data patterns before deciding to estimate
    recruitment deviations or time-varying selectivity first.
