---
title: "Start Year Considerations"
format: html
---

The estimated population age composition in the first year of composition data interacts with the structural stiffness (especially asymptotic selectivity) to produce a strong influence on the model result. Therefore, R0, initial_F, and domed selectivity must be considered together.

## Population age composition in the start year is composed of:
  - An equilibrium age composition using Z = M + initial_F
  - Age-specific deviation from that vector for none, to all, of the ages.
    - These age deviations are a continuation of the recruitment deviations (devs), but now they are centered around the initial equilibrium age composition, rather than around the spawner-recruitment function.
    - Because the devs are centered around the equilibrium age composition, it is important that the initial_F be approximately correct, otherwise a pattern can be introduced in the devs.
    - SS3 provides the concept of early_devs, which are not zero-centered, to separate them from the main_rec_devs, which typically are zero-centered (but growing evidence that they should also be free devs).

**[Need a picture here]**

## Start year considerations

  - Long historical period of relatively stable catch
    - This is the ideal situation for use of initial equilibrium catch with initial_F estimated. Even a low level of catch can have a noticeable impact on the expected occurrence of fish in the plus group if M is low.
    - If that level of catch is moderate, then the most internally consistent approach is to turn on the spawner-recruitment calculations within the initial equilibrium. Note that the ensuing calculation is identical to the MSY calculations. This means that SS3 will always make R0 big enough such that MSY is greater than initial equilibrium catch. If you suspect that historical catch reduced biomass below BMSY, then it is incorrect to use initial equilibrium approach. Instead, move start year earlier, and included the time series of catches that previously were averaged into the initial equilibrium catch.  With this alternative, the time series of catches will be able to create F’s greater than FMSY. Also, what was a vector of initial age composition now appears in the model as a vector of recruitments extending further back in time.
  - Substantial changes in historical catch levels have occurred within a lifespan before start year
    - In this situation, the equilibrium assumption is violated. Better approach is to start earlier and allow estimation of year specific F.


## First year with recdevs
  - By starting rec_devs early (even long before influential data occur) the variability associated with sigmaR creates variance in the population abundance and this variance can be seen in both recruitment and spawning biomass.
**[Need picture here]**
  - The first year with rec_devs (main or early) can be Nages before start year.
  - Devs that occur long before the data do not influence the goodness of fit to the data, but the variance of those devs is still important to capture. Use of the early_devs concept is helpful here because they can wait to be turned on in a late phase just to capture that variance.
  - The challenge with this long vector of devs is that the influence of data on the dev estimation gradually increases over time. So some of the devs may show unexpected patterns because of the influence of noise in the early data. Shortening up the number of years with devs may not help because the influence of the data is still there and the model response often will still show up in the first estimated dev.

::: {.callout-tip title="Think of it as"}
How much of a logL improvement in fit to some early length comp sample is needed to outweigh the logL penalty caused by an early dev moving away from 0.0?
:::

